### ISSUE TITLE
Backend: to grab user's game history

### ISSUE THREAD

**Issue by luke-h-cho** [brkg/coffee_meets_summoner#12]
Assuming that summoner's puuid comes as a part of the request body after clicking on the name to see the game history, we want:

1. search for recent games 
2. search for details from those recent games
3. iterate through a property of API response to find only user's relevant information (use puuid)
4. grab data and send it to the frontend
  a. kill/death/assist
  b. items
  c. which role 
  d. which champ
  e. game result
  f. mastery/summoner spells

**Comment by DarrenChan18** [comment]
Grabbed users game history and able to send back to the front end
